server:
  port: 8082
  servlet:
    context-path: /authapp


spring:
  data:
    mongodb:
      database: test_db
      port: 27017
      host: localhost
      repositories:
        enabled: true

app:
  secret-key: JwtSecretKey
  token:
    expirationTimeInMs: 36000000